---
command: config
body: |
  Modify configuration settings

  Extended usage
  config list               - List configured settings
  config set setting value  - Change setting value

  Possible Settings / Values 
  autoloot    - (on / off)
  brief       - (on / off)
  minimap     - (on / off)

  Example
  config set autoloot on  - Turn on autoloot
